version: 1.0.{build}
branches:
  only:
  - master
  
build:
  verbosity: minimal
  project: src\Logs.sln

before_build:
- ps: nuget restore ./src/Logs.sln

after_test: 
  - src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"src\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  src\Logs.Web.Tests\bin\Debug\Logs.Web.Tests.dll" -output:coverage.xml

  - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml